# List of 38 Tamil Nadu districts and their primary town (district HQ or well-known city)
# These names are used for OpenWeather's city query along with "Tamil Nadu, IN"

DISTRICTS = [
	{"district": "Ariyalur", "query": "Ariyalur"},
	{"district": "Chengalpattu", "query": "Chengalpattu"},
	{"district": "Chennai", "query": "Chennai"},
	{"district": "Coimbatore", "query": "Coimbatore"},
	{"district": "Cuddalore", "query": "Cuddalore"},
	{"district": "Dharmapuri", "query": "Dharmapuri"},
	{"district": "Dindigul", "query": "Dindigul"},
	{"district": "Erode", "query": "Erode"},
	{"district": "Kallakurichi", "query": "Kallakurichi"},
	{"district": "Kanchipuram", "query": "Kanchipuram"},
	{"district": "Kanyakumari", "query": "Nagercoil"},
	{"district": "Karur", "query": "Karur"},
	{"district": "Krishnagiri", "query": "Krishnagiri"},
	{"district": "Madurai", "query": "Madurai"},
	{"district": "Mayiladuthurai", "query": "Mayiladuthurai"},
	{"district": "Nagapattinam", "query": "Nagapattinam"},
	{"district": "Namakkal", "query": "Namakkal"},
	{"district": "Nilgiris", "query": "Udhagamandalam"},
	{"district": "Perambalur", "query": "Perambalur"},
	{"district": "Pudukkottai", "query": "Pudukkottai"},
	{"district": "Ramanathapuram", "query": "Ramanathapuram"},
	{"district": "Ranipet", "query": "Ranipet"},
	{"district": "Salem", "query": "Salem"},
	{"district": "Sivaganga", "query": "Sivaganga"},
	{"district": "Tenkasi", "query": "Tenkasi"},
	{"district": "Thanjavur", "query": "Thanjavur"},
	{"district": "Theni", "query": "Theni"},
	{"district": "Thoothukudi", "query": "Thoothukudi"},
	{"district": "Tiruchirappalli", "query": "Tiruchirappalli"},
	{"district": "Tirunelveli", "query": "Tirunelveli"},
	{"district": "Tirupathur", "query": "Tirupathur"},
	{"district": "Tiruppur", "query": "Tiruppur"},
	{"district": "Tiruvallur", "query": "Tiruvallur"},
	{"district": "Tiruvannamalai", "query": "Tiruvannamalai"},
	{"district": "Tiruvarur", "query": "Tiruvarur"},
	{"district": "Vellore", "query": "Vellore"},
	{"district": "Viluppuram", "query": "Viluppuram"},
	{"district": "Virudhunagar", "query": "Virudhunagar"},
]